[package]
name = "flate_bench"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
flate2 = "*"
inflate = "*"
libflate = {path = "../"}
